main: de.koppy.project.Main
name: Project-A
version: Alpha-v0.12.3
author: Koppitent
description: Alpha-Ready!
api-version: 1.16
commands:
  chunk:
  config:
  gm:
  gamemode:
  land:
  claims:
  fly:
  give:
  i:
  weather:
  head:
  kopf:
  difficulty:
  teleport:
  tp:
  economy:
  eco:
  balance:
  bal:
  money:
  time:
  addsit:
  bank:
  pay:
  moneytoggle:
  job:
  tpa:
  tpaccept:
  tpdeny:
  tptoggle:
  warp:
  invsee:
  help:
  warps:
  setspawn:
  spawn:
  clear:
  setclantag:
  case:
  setpos:
  profile:
  playtime:
  local:
  l:
  spielzeit:
  trade:
  t:
  togglescoreboard:
  sethome:
  removehome:
  msg:
  r:
  home:
  givemecock:
  region:
  ft:
  travel:
  fasttravel:
  setregion: